sudo: required
language: cpp

services:
  - docker

before_install:
  - docker pull peterus/fossasat

jobs:
  include:
    - stage: compile
      script: docker run -t -i -v $PWD/software:/src -w /src peterus/fossasat /bin/bash compile.sh
    - stage: cppcheck
      script: docker run -t -i -v $PWD/software:/src -w /src peterus/fossasat /bin/bash cppcheck.sh
    - doxygen:
      script:
        sudo apt-get update;
        sudo apt-get install -y doxygen;
        doxygen software/Doxyfile;

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: Doxygen/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
