os: linux
services:
  - docker
before_install:
  - docker pull fossasystems/fossasat
script:
  - cd software
  - docker run -t --user 1000:1000 -v $PWD:/home/newuser/src -v $PWD/../Arduino:/home/newuser/Arduino -w /home/newuser/src fossasystems/fossasat /bin/bash scripts/prepare.sh
  - docker run -t --user 1000:1000 -v $PWD:/home/newuser/src -v $PWD/../Arduino:/home/newuser/Arduino -w /home/newuser/src fossasystems/fossasat /bin/bash scripts/compile.sh
  - docker run -t --user 1000:1000 -v $PWD:/home/newuser/src -v $PWD/../Arduino:/home/newuser/Arduino -w /home/newuser/src fossasystems/fossasat /bin/bash scripts/cppcheck.sh
  - docker run -t --user 1000:1000 -v $PWD:/home/newuser/src -v $PWD/../Arduino:/home/newuser/Arduino -w /home/newuser/src fossasystems/fossasat /bin/bash scripts/doxygen.sh
deploy:
  - provider: releases
    skip_cleanup: true
    file:
      - FossaSat1B/FossaSat1B.arduino.avr.pro.hex
      - FossaSat1B/FossaSat1B.arduino.avr.pro.with_bootloader.hex
      - FossaSat1B/FossaSat1B.arduino.avr.pro.elf
      - FossaSat1B/FossaSat1B.arduino.avr.pro.nm.txt
      - FossaSat1B/FossaSat1B.arduino.avr.pro.lst.txt
      - FossaSat1B/FossaSat1B.MiniCore.avr.328.hex
      - FossaSat1B/FossaSat1B.MiniCore.avr.328.with_bootloader.hex
      - FossaSat1B/FossaSat1B.MiniCore.avr.328.elf
      - FossaSat1B/FossaSat1B.MiniCore.avr.328.nm.txt
      - FossaSat1B/FossaSat1B.MiniCore.avr.328.lst.txt
    token: $GH_REPO_TOKEN
    name: Build $(date +'%d.%m.%Y %R')
    draft: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: software/Doxygen/html
    token: $GH_REPO_TOKEN
    on:
      branch: master
