os: linux
services:
  - docker
before_install:
  - docker pull peterus/fossasat
script:
  - cd software
  - docker run -t -i -v $PWD:/src -w /src peterus/fossasat /bin/bash compile.sh
  - docker run -t -i -v $PWD:/src -w /src peterus/fossasat /bin/bash cppcheck.sh
  - docker run -t -i -v $PWD:/src -w /src peterus/fossasat /bin/bash doxygen.sh
deploy:
  - provider: releases
    skip_cleanup: true
    file:
      - FossaSat1B/FossaSat1B.arduino.avr.uno.hex
      - FossaSat1B/FossaSat1B.arduino.avr.uno.with_bootloader.hex
      - FossaSat1B/FossaSat1B.arduino.avr.uno.elf
    token: $GH_REPO_TOKEN
    name: Build $(date +'%d.%m.%Y %R')
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: software/Doxygen/html
    token: $GH_REPO_TOKEN
    on:
      branch: master
