sudo: required
language: cpp

services:
  - docker

before_install:
  - docker pull peterus/fossasat

jobs:
  include:
    - stage: compile
      script: docker run -t -i -v $PWD/software:/src -w /src peterus/fossasat /bin/bash compile.sh
    - stage: cppcheck
      script: docker run -t -i -v $PWD/software:/src -w /src peterus/fossasat /bin/bash cppcheck.sh

