name: CI

on: [push, pull_request]

jobs:
  Arduino-AtMega328P:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.local/bin
      - run: echo "::add-path::~/.local/bin"
      - run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh
      - run: arduino-cli core update-index
      - run: arduino-cli lib update-index
      - run: arduino-cli core install arduino:avr@1.8.2
      - run: arduino-cli lib install RadioLib
      - run: git clone https://github.com/FOSSASystems/FOSSA-Comms.git $HOME/Arduino/libraries/FOSSA-Comms
      - run: git clone https://github.com/FOSSASystems/tiny-AES-c.git $HOME/Arduino/libraries/tiny-AES-c
      - run: git clone https://github.com/jarzebski/Arduino-INA226.git $HOME/Arduino/libraries/Arduino-INA226
      - run: git clone https://github.com/canique/Low-Power-Canique.git $HOME/Arduino/libraries/Low-Power
      - uses: actions/checkout@v2
      - run: cd software && arduino-cli compile -v --fqbn arduino:avr:pro:cpu=8MHzatmega328 FossaSat1B --warnings=all --build-path=$PWD/avr-build/

  Arduino-AtMega328PB:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.local/bin
      - run: echo "::add-path::~/.local/bin"
      - run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh
      - run: arduino-cli core update-index --additional-urls https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
      - run: arduino-cli core install MiniCore:avr arduino:avr@1.8.2 --additional-urls https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
      - run: arduino-cli lib update-index
      - run: arduino-cli lib install RadioLib
      - run: git clone https://github.com/FOSSASystems/FOSSA-Comms.git $HOME/Arduino/libraries/FOSSA-Comms
      - run: git clone https://github.com/FOSSASystems/tiny-AES-c.git $HOME/Arduino/libraries/tiny-AES-c
      - run: git clone https://github.com/jarzebski/Arduino-INA226.git $HOME/Arduino/libraries/Arduino-INA226
      - run: git clone https://github.com/canique/Low-Power-Canique.git $HOME/Arduino/libraries/Low-Power
      - uses: actions/checkout@v2
      - run: cd software && arduino-cli compile -v --fqbn MiniCore:avr:328:bootloader=uart0,variant=modelPB,BOD=1v8,LTO=Os_flto,clock=8MHz_internal FossaSat1B --warnings=all --build-path=$PWD/avr-build/

  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential
      - run: git clone git://github.com/danmar/cppcheck.git ~/cppcheck
      - run: mkdir ~/cppcheck/build
      - run: cd ~/cppcheck/build && cmake .. && cmake --build . && cmake install
      - run: cd ~/cppcheck/build && ls -al && tree


