name: CI

on: [push, pull_request]

jobs:
  Arduino-AtMega328P:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.local/bin
      - run: echo "::add-path::~/.local/bin"
      - run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh
      - run: arduino-cli core update-index
      - run: arduino-cli lib update-index
      - run: arduino-cli core install arduino:avr@1.8.2
      - run: arduino-cli lib install RadioLib
      - run: git clone https://github.com/FOSSASystems/FOSSA-Comms.git $HOME/Arduino/libraries/FOSSA-Comms
      - run: git clone https://github.com/FOSSASystems/tiny-AES-c.git $HOME/Arduino/libraries/tiny-AES-c
      - run: git clone https://github.com/jarzebski/Arduino-INA226.git $HOME/Arduino/libraries/Arduino-INA226
      - run: git clone https://github.com/canique/Low-Power-Canique.git $HOME/Arduino/libraries/Low-Power
      - uses: actions/checkout@v2
      - run: cd software && arduino-cli compile -v --fqbn arduino:avr:pro:cpu=8MHzatmega328 --build-properties compiler.cpp.extra_flags=-DRADIOLIB_STATIC_ONLY FossaSat1B --warnings=all --build-path=$PWD/avr-build/
      - uses: actions/upload-artifact@v2
        with:
          name: Arduino-AtMega328P
          path: software/avr-build/*.hex
      - uses: actions/upload-artifact@v2
        with:
          name: Arduino-AtMega328P
          path: software/avr-build/*.elf

  Arduino-AtMega328PB:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.local/bin
      - run: echo "::add-path::~/.local/bin"
      - run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh
      - run: arduino-cli core update-index --additional-urls https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
      - run: arduino-cli core install MiniCore:avr arduino:avr@1.8.2 --additional-urls https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
      - run: arduino-cli lib update-index
      - run: arduino-cli lib install RadioLib
      - run: git clone https://github.com/FOSSASystems/FOSSA-Comms.git $HOME/Arduino/libraries/FOSSA-Comms
      - run: git clone https://github.com/FOSSASystems/tiny-AES-c.git $HOME/Arduino/libraries/tiny-AES-c
      - run: git clone https://github.com/jarzebski/Arduino-INA226.git $HOME/Arduino/libraries/Arduino-INA226
      - run: git clone https://github.com/canique/Low-Power-Canique.git $HOME/Arduino/libraries/Low-Power
      - uses: actions/checkout@v2
      - run: cd software && arduino-cli compile -v --fqbn MiniCore:avr:328:bootloader=uart0,variant=modelPB,BOD=1v8,LTO=Os_flto,clock=8MHz_internal --build-properties compiler.cpp.extra_flags=-DRADIOLIB_STATIC_ONLY FossaSat1B --warnings=all --build-path=$PWD/avr-build/
      - uses: actions/upload-artifact@v2
        with:
          name: Arduino-AtMega328PB
          path: software/avr-build/*.hex
      - uses: actions/upload-artifact@v2
        with:
          name: Arduino-AtMega328PB
          path: software/avr-build/*.elf

  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install snapd && sudo snap install cppcheck
      - run: cppcheck --version
      - uses: actions/checkout@v2
      - run: cd software && cppcheck --language=c++ -f -DRADIOLIB_VERSION=0xF0000000 -DRADIOLIB_STATIC_ONLY --enable=all --suppress=missingIncludeSystem --inconclusive --inline-suppr --error-exitcode=1 -IFossaSat1B FossaSat1B FossaSat1B/FossaSat1B.ino

  doxygen:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install --no-install-recommends doxygen graphviz
      - run: doxygen --version
      - uses: actions/checkout@v2
      - run: cd software && doxygen Doxyfile
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: software/Doxygen/html

  PlatformIO-Build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: pip3 install platformio
      - run: echo "::add-path::~/.local/bin"
      - uses: actions/checkout@v2
      - run: cd software && platformio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high
      - run: cd software && platformio run -v

  PlatformIO-UnitTest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: platformio update
      - run: cd software && platformio test -e ATmega328PB -v
